import './globals.css'
import styles from './layout.module.css'
import { Inter } from 'next/font/google'
import { NavMenu } from 'src/components/nav-menu'
import { Footer } from "src/components/footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Movie Library',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${styles.rootLayout} ${inter.className}`}>
        <header>
          <NavMenu />
        </header>

        <main>{children}</main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
